{% set version = "0.6.2" %}

package:
  name: pytest-jupyter-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-jupyter/pytest_jupyter-{{ version }}.tar.gz
  sha256: 47f80f573384f274470282d044cd2566b81d7379112446f69adb1fcdfc3351ca

build:
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - python

outputs:
  - name: pytest-jupyter
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools
        - hatchling 1.12.2
      run:
        - python
        - jupyter_core
        - pytest
      run_constrained:
        - jupyter_server >=1.21
        - jupyter_client >=7.4.0
        - ipykernel >=6.14
        - nbformat >=5.3
    test:
      source_files:
        - tests
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_core
      commands:
        - pip check
      requires:
        - pip

  - name: pytest-jupyter-client
    requirements:
      host:
        - python
        - setuptools
        - wheel
      run:
        - {{ pin_subpackage("pytest-jupyter", max_pin="x.x.x") }}
        - ipykernel >=6.14
        - jupyter_client >=7.4.0
        - python
    test:
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_client
      commands:
        - pip check
      requires:
        - pip

  - name: pytest-jupyter-server
    requirements:
      host:
        - python
        - setuptools
        - wheel
      run:
        - {{ pin_subpackage("pytest-jupyter-client", max_pin="x.x.x") }}
        - jupyter_server >=1.21
        - nbformat >=5.3
        - python
    test:
      source_files:
        - tests
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_server
      commands:
        - pip check
        - cd tests && pytest -vv 
      requires:
        - pip

about:
  home: https://pypi.org/project/pytest-jupyter
  description: A pytest plugin for testing Jupyter libraries and extensions.
  summary: |
    Pytest plugin that provides a set of fixtures and markers for testing Jupyter notebooks and 
    Jupyter kernel sessions using the Pytest framework. This package allows developers to run 
    tests on Jupyter notebooks as if they were regular Python modules.
  doc_url: https://pytest-jupyter.readthedocs.io/en/main/
  dev_url: https://github.com/jupyter-server/pytest-jupyter
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  feedstock-name: pytest-jupyter
  recipe-maintainers:
    - blink1073
    - fcollonval
    - conda-forge/jupyter_server
