{% set version = "0.10.1" %}

package:
  name: pytest-jupyter-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-jupyter/pytest_jupyter-{{ version }}.tar.gz
  sha256: 00df54eef9e201dd542d5471b8980def15d34b917b30587d14d7c824fc4d9e84

build:
  number: 1
  skip: true  # [py<38]

requirements:
  host:
    - python

outputs:
  - name: pytest-jupyter
    script: build-pkg.bat # [win]
    script: build-pkg.sh  # [unix]
    requirements:
      host:
        - python
        - pip
        - hatchling >=1.10.0
      run:
        - python
        - jupyter_core >=5.7
        - pytest >=7.0
      run_constrained:
        - jupyter_server >=1.21
        - jupyter_client >=7.4.0
        - ipykernel >=6.14
        - nbformat >=5.3
    test:
      source_files:
        - tests
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_core
      commands:
        - pip check
      requires:
        - pip

  - name: pytest-jupyter-client
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("pytest-jupyter", max_pin="x.x.x") }}
        - ipykernel >=6.14
        - jupyter_client >=7.4.0
        - nbformat >=5.3
        - python
    test:
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_client
      commands:
        - pip check
      requires:
        - pip

  - name: pytest-jupyter-server
    build:
      skip: true # [s390x] no nodejs for jupyter_server
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("pytest-jupyter-client", max_pin="x.x.x") }}
        - jupyter_server >=1.21
        - jupyter_client >=7.4.0
        - nbformat >=5.3
        - ipykernel >=6.14
        - python
    test:
      source_files:
        - tests
      imports:
        - pytest_jupyter
        - pytest_jupyter.jupyter_server
      commands:
        - pip check
        - cd tests && pytest -vv 
      requires:
        - pip

about:
  home: https://pypi.org/project/pytest-jupyter
  description: A pytest plugin used for testing Jupyter libraries and extensions.
  summary: |
    Pytest plugin that provides a set of fixtures and markers for testing Jupyter notebooks and 
    Jupyter kernel sessions using the Pytest framework. This package allows developers to run 
    tests on Jupyter notebooks as if they were regular Python modules.
  doc_url: https://pytest-jupyter.readthedocs.io/en/main/
  dev_url: https://github.com/jupyter-server/pytest-jupyter
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  feedstock-name: pytest-jupyter
  recipe-maintainers:
    - blink1073
    - fcollonval
    - conda-forge/jupyter_server
